function () {
          assert.instanceOf(error, Error);
        }