function() {
                s.emit('error', errnoException(errno, 'bind'));
            }