function(err) {
    self.onError(err)
  }